name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - name: apt update
      run: sudo apt update
    - name: install requirements
      run: sudo apt install doxygen libboost-all-dev
    - uses: actions/checkout@v2-beta
      with:
        repository: zhouzhenghui/static_assert
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make install
      run: sudo make install
    - uses: actions/checkout@v2-beta
      with:
        repository: zhouzhenghui/preprocessor
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make install
      run: sudo make install
    - uses: actions/checkout@v1
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
